export enum TEAM_KEYS {
  ALL_TEAMS = 'ALL_TEAMS',
  CHANGE_STATUS = 'CHANGE_STATUS',
  UPDATE_PERMISSIONS = 'UPDATE_TEAM_PERMISSIONS',
  MEMBER_IMPACT = 'MEMBER_IMPACT',
  REMOVE_MEMBER = 'REMOVE_MEMBER',
  RESET_TWO_FACTOR = 'RESET_TWO_FACTOR',
}
