import { CgCreditCard, CgSync } from 'react-icons/cg';
import {
  CiBellOff,
  CiBellOn,
  CiCloudOn,
  CiFilter,
  CiGrid42,
  CiLogout,
  CiMap,
  CiMapPin,
  CiMobile3,
  CiPlay1,
  CiSaveDown2,
  CiStar,
  CiUser,
  CiViewList,
  CiWarning,
} from 'react-icons/ci';
import { FaBook, FaUsers } from 'react-icons/fa6';
import { FaCog, FaGoogleDrive, FaUserAlt, FaUserPlus } from 'react-icons/fa';
import { HiOutlineInformationCircle, HiOutlineMail } from 'react-icons/hi';
import {
  HiHeart,
  HiHome,
  HiMiniChevronLeft,
  HiMiniChevronRight,
  HiMiniMegaphone,
  HiMiniPlusSmall,
  HiOutlineFolderOpen,
  HiOutlineWrenchScrewdriver,
} from 'react-icons/hi2';
import {
  IoIosArrowRoundBack,
  IoIosArrowRoundForward,
  IoIosCheckmark,
  IoIosClose,
  IoIosGitPullRequest,
  IoIosHelpCircle,
  IoIosTrendingUp,
  IoMdFingerPrint,
} from 'react-icons/io';
import {
  IoBarChartOutline,
  IoBedOutline,
  IoChatbubblesOutline,
  IoCheckmarkDone,
  IoDocumentTextOutline,
  IoLockClosed,
  IoMic,
  IoPause,
  IoPlay,
  IoRocketSharp,
  IoShieldCheckmarkSharp,
} from 'react-icons/io5';
import { RiMailSendLine, RiSearch2Line } from 'react-icons/ri';
import {
  TbFileDownload,
  TbLayoutSidebarRightCollapse,
  TbLayoutSidebarRightExpand,
  TbSparkles,
  TbTaxEuro,
} from 'react-icons/tb';
import { FaTrashAlt } from 'react-icons/fa';
import { IoCopyOutline, IoDownloadOutline, IoKeyOutline, IoShareOutline } from 'react-icons/io5';
import { MdAssignmentInd, MdEdit, MdLocalPhone, MdWallet } from 'react-icons/md';
import { PiBathtubLight, PiEyeLight } from 'react-icons/pi';
import { GrMoney } from 'react-icons/gr';
import { TbRestore } from 'react-icons/tb';
import { RxDotsHorizontal, RxHamburgerMenu, RxLapTimer } from 'react-icons/rx';
import {
  LuBuilding2,
  LuClipboardList,
  LuFile,
  LuFileImage,
  LuFiles,
  LuHeartHandshake,
  LuMaximize,
  LuSend,
  LuLayoutDashboard,
  LuHouse,
  LuLandPlot,
  LuMegaphone,
  LuCalendarCheck,
  LuCalendarClock,
  LuMessagesSquare,
  LuReceipt,
  LuPalette,
  LuUsers,
  LuUserPlus,
  LuStore,
  LuCreditCard,
  LuPlug,
  LuUserRound,
  LuShieldCheck,
  LuBell,
  LuLandmark,
  LuBriefcase,
  LuWallet,
  LuUserCog,
  LuSettings2,
} from 'react-icons/lu';
import { BsCalendar3, BsSliders } from 'react-icons/bs';
import { CiGrid31 } from 'react-icons/ci';
import { ImOffice } from 'react-icons/im';
import { GoZap } from 'react-icons/go';
import { BiChevronDown, BiWorld } from 'react-icons/bi';
import { FiMinus, FiTarget } from 'react-icons/fi';
import { FcGoogle } from 'react-icons/fc';
import { IoTicket } from 'react-icons/io5';
import { MdOutlineQueryStats } from 'react-icons/md';
import { IoStatsChartSharp } from 'react-icons/io5';

export const Icons = {
  MapPin: CiMapPin,
  Map: CiMap,
  Mail: HiOutlineMail,
  User: CiUser,
  Close: IoIosClose,
  RiBuildingLine: LuBuilding2,
  FaUsers: FaUsers,
  FaUserAlt: FaUserAlt,
  IoIosArrowRoundBack,
  IoIosHelpCircle,
  Home: HiHome,
  TbTax: TbTaxEuro,
  PlusMinus: HiMiniPlusSmall,
  Filter: CiFilter,
  Save: CiSaveDown2,
  Refresh: CgSync,
  Paper: IoDocumentTextOutline,
  Copy: IoCopyOutline,
  Download: IoDownloadOutline,
  DownloadPaper: TbFileDownload,
  Key: IoKeyOutline,
  Share: IoShareOutline,
  Edit: MdEdit,
  View: PiEyeLight,
  Payment: GrMoney,
  Restore: TbRestore,
  Trash: FaTrashAlt,
  Logout: CiLogout,
  Menu: RxHamburgerMenu,
  CreditCard: CgCreditCard,
  Wrench: HiOutlineWrenchScrewdriver,
  Shield: IoShieldCheckmarkSharp,
  Chart: IoBarChartOutline,
  Trending: IoIosTrendingUp,
  UserPlus: FaUserPlus,
  Check: IoIosCheckmark,
  DoubleCheck: IoCheckmarkDone,
  ArrowRight: IoIosArrowRoundForward,
  Play: CiPlay1,
  Bath: PiBathtubLight,
  Bed: IoBedOutline,
  Maximize: LuMaximize,
  Phone: MdLocalPhone,
  Heart: HiHeart,
  Search: RiSearch2Line,
  Slider: BsSliders,
  Chat: IoChatbubblesOutline,
  Bell: CiBellOn,
  Setting: FaCog,
  List: CiViewList,
  Grid: CiGrid31,
  DotHorizontal: RxDotsHorizontal,
  SideOpen: TbLayoutSidebarRightExpand,
  SideClose: TbLayoutSidebarRightCollapse,
  Office: ImOffice,
  Send: LuSend,
  Timer: RxLapTimer,
  Request: IoIosGitPullRequest,
  FolderOpen: HiOutlineFolderOpen,
  BellOff: CiBellOff,
  Clipboard: LuClipboardList,
  Warn: CiWarning,
  Zap: GoZap,
  Mobile: CiMobile3,
  World: BiWorld,
  LuHeartHandshake,
  Calendar: BsCalendar3,
  TrendingUp: IoIosTrendingUp,
  Star: CiStar,
  TbSparkles,
  Target: FiTarget,
  Rocket: IoRocketSharp,
  Cloud: CiCloudOn,
  Google: FcGoogle,
  GoogleDrive: FaGoogleDrive,
  GridHome: CiGrid42,
  Minus: FiMinus,
  SendMail: RiMailSendLine,
  Lock: IoLockClosed,
  Megaphone: HiMiniMegaphone,
  Wallet: MdWallet,
  Assignment: MdAssignmentInd,
  Agenda: FaBook,
  ChevronLeft: HiMiniChevronLeft,
  ChevronRight: HiMiniChevronRight,
  Ticket: IoTicket,
  QueryStats: MdOutlineQueryStats,
  StatsChart: IoStatsChartSharp,
  FingerPrint: IoMdFingerPrint,
  InfoIcon: HiOutlineInformationCircle,
  ChevronDown: BiChevronDown,
  LuFiles,
  LuFileImage,
  LuFile,
  VoicePlay: IoPlay,
  VoicePause: IoPause,
  Mic: IoMic,
};

/**
 * Icônes du menu latéral : un seul jeu (Lucide, trait identique) et une icône par entrée, pour
 * que chaque lien se reconnaisse d'un coup d'œil, même menu replié.
 */
export const NavIcons = {
  Dashboard: LuLayoutDashboard,
  Properties: LuHouse,
  Buildings: LuBuilding2,
  Lands: LuLandPlot,
  Annonces: LuMegaphone,
  Bookings: LuCalendarCheck,
  Visits: LuCalendarClock,
  Messages: LuMessagesSquare,
  Invoices: LuReceipt,
  InvoiceTemplates: LuPalette,
  Team: LuUsers,
  Invitations: LuUserPlus,
  Agency: LuStore,
  Subscription: LuCreditCard,
  Integrations: LuPlug,
  Profile: LuUserRound,
  Security: LuShieldCheck,
  Notifications: LuBell,
  // Titres des groupes
  GroupAssets: LuLandmark,
  GroupActivity: LuBriefcase,
  GroupBilling: LuWallet,
  GroupTeam: LuUserCog,
  GroupAgency: LuSettings2,
  GroupAccount: LuUserRound,
};
