export enum INVITE_KEYS {
  CREATE_INVITATION = 'CREATE_INVITATION',
  ACCEPT_INVITATION = 'ACCEPT_INVITATION',
  PREVIEW_INVITATION = 'PREVIEW_INVITATION',
  SEND_INVITATION_CODE = 'SEND_INVITATION_CODE',
  CANCEL_INVITATION = 'CANCEL_INVITATION',
  RESEND_INVITATION = 'RESEND_INVITATION',
  INVITATION_AGENCY_LIST = 'INVITATION_AGENCY_LIST',
}
