export enum BUILDING_KEYS {
  CREATE_BUILDING = 'CREATE_BUILDING',
  UPDATE_BUILDING = 'UPDATE_BUILDING',
  DELETE_BUILDING = 'DELETE_BUILDING',
  BUILDING_IMPACT = 'BUILDING_IMPACT',
  ALL_BUILDING_BY_AGENCY = 'ALL_BUILDING_BY_AGENCY',
}
