export enum USERS_KEYS {
  GET_USER_INFO = 'GET_USER_INFO',
  UPDATE_USER_INFO = 'UPDATE_USER_INFO',
  PASSKEY_SESSIONS = 'PASSKEY_SESSIONS',
  BACKUP_CODES_REMAINING = 'BACKUP_CODES_REMAINING',
  CHECK_EMAIL = 'CHECK_EMAIL',
}
