export enum AUTH_KEYS {
  REGISTER_USER = 'REGISTER_USER',
  FORGET_PASSWORD_INIT = 'FORGET_PASSWORD_INIT',
  RESET_PASSWORD = 'RESET_PASSWORD',
  SEND_EMAIL_VERIFICATION = 'SEND_EMAIL_VERIFICATION',
  CHECK_EMAIL = 'CHECK_EMAIL',
  TWO_FACTOR_RECOVERY_REQUEST = 'TWO_FACTOR_RECOVERY_REQUEST',
  TWO_FACTOR_RECOVERY_CONFIRM = 'TWO_FACTOR_RECOVERY_CONFIRM',
  TWO_FACTOR_RECOVERY_CANCEL = 'TWO_FACTOR_RECOVERY_CANCEL',
}
